nohup uv run train_gliznet.py \
    --model_name sentence-transformers/all-MiniLM-L6-v2 \
    --run_name "gliznet_training" \
    --projected_dim 256 \
    --similarity_metric dot \
    --max_labels 20 \
    --per_device_train_batch_size 32 \
    --per_device_eval_batch_size 64 \
    --num_train_epochs 50 \
    --output_dir results \
    --learning_rate 1e-4 \
    --logging_steps 50 \
    --warmup_steps 10 \
    --weight_decay 1e-4 \
    --eval_steps 50 \
    --save_steps 50 \
    --eval_strategy epoch \
    --save_strategy epoch \
    --save_total_limit 2 \
    --load_best_model_at_end \
    --metric_for_best_model eval_loss \
    --dataloader_pin_memory \
    --dataloader_num_workers 4 \
    --remove_unused_columns False \
    --report_to wandb \
    --lr_scheduler_type cosine \
    --fp16 \
    --eval_do_concat_batches False \
    --data_seed 42 \
    &> nohup.out &